### ISSUE TITLE
mistake in RegistersUsers.php

### ISSUE THREAD

**Issue by hatamiarash7** [LavaLite/framework#36]
Hi
There is a little problem in this class.

At line 75 in **create** function : 

```
$data = [
    'name'      => $data['name'],
    'email'     => $data['email'],
    'password'  => $data['password'];
    'api_token' => str_random(60),
    ];
```

`` 'password'  => $data['password']; `` is wrong ... replace ``;`` with``,``

**Comment by gachowy** [comment]
Fix is waiting for merge:
https://github.com/LavaLite/framework/pull/35
