### ISSUE TITLE
Call to undefined method Litepie\Trans\Trans::isMultilingual()

### ISSUE THREAD

**Issue by agasigp** [LavaLite/framework#47]
When i run composer update, it shows Call to undefined method Litepie\Trans\Trans::isMultilingual() I'm using lavalite 4.1
![Screenshot_2019-05-08_16-36-02](https://user-images.githubusercontent.com/2476867/57365708-caf85a80-71af-11e9-8231-2d6becbf9242.png)

**Comment by RenfosTech** [comment]
Bug fixed

Run `composer update` and try again
